language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then openssl aes-256-cbc -K $encrypted_d4931f6d241c_key -iv $encrypted_d4931f6d241c_iv -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d; fi
    - composer self-update
    - composer update
    - composer install

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then ./psh ci-small; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then ./psh ci-small; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then ./psh unit; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then ./psh unit; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./psh build; fi
    - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./deploy.sh; fi
